language: csharp
solution: openssl.net.sln

os:
 - osx
 - linux

before_install:
 - wget https://www.openssl.org/source/openssl-1.0.2a.tar.gz
 - tar zxvf openssl-1.0.2a.tar.gz
 - ( cd openssl-1.0.2a && ./config && make -j4 && sudo make install )

install:
  - nuget restore openssl.net.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release openssl.net.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Release/UnitTests.dll
